### ISSUE TITLE
Test 212 adding functionality to process files through icap server using docker command

### ISSUE THREAD

**Issue by asloman** [filetrust/icap-management-ui-tests#162]

**Comment by vfedrunov** [comment]
It's possible to run Docker command inside a test using the following function

`icap-management-ui-tests/src/utils/steps_file.js`
```
sendFileICAP: function(file) {
    require('child_process').execSync(`cd ../p-ui-wireframes/ && docker run -v <localfolderinput>:/opt -v <localfolderoutput>:/home glasswallsolutions/c-icap-client:manual-v1 -s 'gw_rebuild' -i <icap-endpoint> -f '/opt/${file}' -o /home/<outputfilename> -v && cd ../icap-management-ui-tests/`, function(err, stdout, stderr) {
        if (err) {
            console.log('err ' + err);
        }
      });
  }
 ```
 To use `I.sendFileICAP(file)`
 
But we have to decide how to run this command inside the pipeline

**Comment by vfedrunov** [comment]
Please, review the [PR](https://github.com/filetrust/icap-management-ui-tests/pull/173)

**Comment by vfedrunov** [comment]
Please review [PR](https://github.com/filetrust/icap-management-ui-tests/pull/176)
