### ISSUE TITLE
Non Compliant Files routing mechanism Test-233 Failing

### ISSUE THREAD

**Issue by asloman** [filetrust/icap-management-ui-tests#164]
Test 233 currently failing. Can use a similar approach as what is used in #162

**Comment by vfedrunov** [comment]
Hi
@asloman, @NadHodeGW have I fix this error? 
![image](https://user-images.githubusercontent.com/50262512/104232754-c83b1780-541e-11eb-9bd4-cc2b2e73f73a.png)

**Comment by NadHodeGW** [comment]
This is now done as part of 130
