### ISSUE TITLE
Request-History-Filtering-by-file-type Test-180 Failing

### ISSUE THREAD

**Issue by asloman** [filetrust/icap-management-ui-tests#167]
Test 180 failing. Appears to also be running 2 tests, when only 1 test condition given.

Logs:![2020-12-23_16h44_03.png](https://images.zenhubusercontent.com/5f3d07cddacb511232da95f0/2bf4e0c9-9ef6-494c-a614-d092eeb2f493)

**Comment by vfedrunov** [comment]
[Done](https://github.com/filetrust/icap-management-ui-tests/pull/170)
